# Generated by Django 5.0.6 on 2024-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("delivery", models.CharField(max_length=100)),
                ("actual_price", models.FloatField()),
                ("discounted_price", models.FloatField()),
            ],
        ),
    ]
