# Generated by Django 5.0.6 on 2024-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="actual_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.IntegerField(),
        ),
    ]
