# Generated by Django 5.0.6 on 2024-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_product_actual_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="actual_price",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.CharField(max_length=200),
        ),
    ]
